graphql server + stats query, deprecate owner column - wip -
holaplex/hub-analytics pull request #5
Opened 2023-08-14 23:40 UTC by mpwsh

2023-08-15 07:41 UTC, kespinola requested changes

2023-08-15 07:41 UTC, kespinola commented on app/src/cube_client.rs
> +    }
More common to have this a new fn on the client that accepts cube args as an argument.

2023-08-15 07:41 UTC, kespinola commented on app/src/cube_client.rs
> +    }
If new returns an instance of a client you can drop this.

2023-08-15 07:41 UTC, kespinola commented on app/src/cube_client.rs
> +    pub async fn execute_query(&self, query_builder: Query) -> Result<String, CubeClientError> {
```suggestion
    pub async fn query(&self, query_builder: Query) -> Result<String, CubeClientError> {
```

Can do it like this or have execute on the query builder that accepts a client.

2023-08-15 07:41 UTC, kespinola commented on app/src/graphql/objects/collection.rs
> +        limit: Option<i32>,
I try to avoid arguments to object fields because can get into n+1 since dataloaders can't take arguments but looking at this it's unavoidable.

2023-08-15 07:41 UTC, kespinola commented on app/src/graphql/objects/collection.rs
> +        limit: Option<i32>,
Thinking something like this so we offer fixed dimensions and less parameters. This works by passing parent context arguments down to lower objects.

```graphql
query {
  collection(id: Uuid) {
     analytics(startTime: DateTime, endTime: DateTime): CollectionAnalytics {
       mints {
         chart {
           count
           timestamp {
             day
           }
         }
         change {
           current
           previous
         }
       }
     }
   }
}
```

2023-08-15 08:40 UTC, kespinola commented on app/src/graphql/objects/collection.rs
> +        limit: Option<i32>,
```graphql
query {
  project(id: Uuid) {
    analytics(startTime: DateTime, endTime: DateTime, timeInterval: TimeInterval): ProjectAnalytics {
        customers {
           chart {
              count
              timestamp {
                day
              }
           }
        }
        mints {
          barChart: chart {
            count
            timestamp
          }
          pieChart: chart {
            count
            project { # this can be a apollo lookup where it uses the project_id on the data point to lookup the project 
              id
              name
            }
          }
        }
    }
  }
}
```

2023-08-18 06:35 UTC, mpwsh commented
moved timestamp to the root of the response, so we can return a single response with merged datapoints using the date as key
```graphql
query {
  analytics(
    projectId: "833465c4-e95d-4868-9c52-923bd12a4032"
    limit: 5000
    interval: THIS_YEAR
    order: ASC
  ) {
    mints {
      count
      collectionId
    }
    collections  {
      count
      projectId
      organizationId
    }
    wallets {
      count
      projectId
    }
    customers {
      count
      projectId
    }
    timestamp
  }
}
```


response:
```json
{
  "data": {
    "analytics": [
      {
        "mints": [
          {
            "count": 1,
            "collectionId": "2f1c2bed-ec7b-4824-a926-02c71438addc"
          },
          {
            "count": 1,
            "collectionId": "764eac2f-8f3a-4edd-a98b-71eb96072351"
          }
        ],
        "collections": null,
        "wallets": [
          {
            "count": 1,
            "projectId": "833465c4-e95d-4868-9c52-923bd12a4032"
          }
        ],
        "customers": [
          {
            "count": 1,
            "projectId": "833465c4-e95d-4868-9c52-923bd12a4032"
          }
        ],
        "timestamp": "2023-06-26T00:00:00"
      },
      {
        "mints": null,
        "collections": [
          {
            "count": 1,
            "projectId": "833465c4-e95d-4868-9c52-923bd12a4032",
            "organizationId": "c0871e8f-6c87-44dd-b5e7-d8379e41f718"
          }
        ],
        "wallets": null,
        "customers": null,
        "timestamp": "2023-06-23T00:00:00"
      },
      {
        "mints": null,
        "collections": [
          {
            "count": 1,
            "projectId": "833465c4-e95d-4868-9c52-923bd12a4032",
            "organizationId": "c0871e8f-6c87-44dd-b5e7-d8379e41f718"
          }
        ],
        "wallets": null,
        "customers": null,
        "timestamp": "2023-06-21T00:00:00"
      },
   ]
 }
}
```

2023-08-19 17:53 UTC, merged